<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}


nav {
    background-color:#19BB9B       ;
    color: white;
}
button {
    background-color: #2f2f2f;
    color: white;
}

</style>
<div class="row">
    <nav class="navbar ">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Money Tracking</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="<?php echo APP_URL . "transacciones/index"; ?>">Transacciones</a></li>
                <li><a href="<?php echo APP_URL . "cuentas/index"; ?>">Cuentas</a></li>
                <li class="active"><a href="<?php echo APP_URL . "categorias/index"; ?>">Categorías</a></li>
            </ul>
        </div>
    </nav>
    <div class="col-sm-8"><h3>Listado de categorías</h3></div>
</div>

</br>

<div class="table-responsive">
    <table class="table table-hover table-bordered table-condensed ">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
        </tr>
        <?php foreach ($this->categorias as $categoria): ?>
            <tr>
                <td><?php echo $categoria["id"]; ?></td>
                <td><?php echo $categoria["name"]; ?></td>
                <td>
                    <a href="<?php echo APP_URL . "categorias/editar/" . $categoria["id"]; ?>">
                        <span class="glyphicon"> </span>
                    </a> |
                    <a onclick="if(!confirm('¿Desea eliminar la categoría seleccionada?')) return false;"
                       href="<?php echo APP_URL . "categorias/eliminar/" . $categoria["id"]; ?>">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
<div class="col-sm-8">
    <a href="<?php echo APP_URL . "categorias/agregar"; ?>">
        <button type="button" class="btn-primary add">
            <span class="glyphicon glyphicon-plus">Agregar</span>
        </button>
    </a>
</div>
